// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgmlifvhpekendfvelae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnbWxpZnZocGVrZW5kZnZlbGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzIwMDksImV4cCI6MjA2Mzk0ODAwOX0.9Cz-rv0d_Sg7MtQqKvdaywP1ESBuaIAhjW4MI_uqHmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);